# Generated by Django 5.2.1 on 2025-06-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_question_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
